### ISSUE TITLE
Error of "ModuleNotFoundError: No module named 'roman'" when running numbers-parser 2.3.3

### ISSUE THREAD

**Issue by traceymeng** [masaccio/numbers-parser#12]
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/traceymeng/git/locAutomation/quickAutomation/lib/tsttManager.py", line 13, in <module>
    from numbers_parser import Document
  File "/Users/traceymeng/Library/Python/3.9/lib/python/site-packages/numbers_parser/__init__.py", line 25, in <module>
    from numbers_parser.document import Document  # NOQA
  File "/Users/traceymeng/Library/Python/3.9/lib/python/site-packages/numbers_parser/document.py", line 5, in <module>
    from numbers_parser.model import NumbersModel
  File "/Users/traceymeng/Library/Python/3.9/lib/python/site-packages/numbers_parser/model.py", line 4, in <module>
    from roman import toRoman
ModuleNotFoundError: No module named 'roman'
python-BaseException

Process finished with exit code 1

**Comment by traceymeng** [comment]
Fixed after I install roman separately.

**Comment by masaccio** [comment]
Reopening as this is a bug: the package should include roman as a dependency. So I will keep the issue open until I fix some time this week.

**Comment by masaccio** [comment]
v2.3.4 now depends upon roman, but workaround was to install manually as you spotted
