### ISSUE TITLE
Unable to import Document on 3.0: TypeError: getattr(): attribute name must be string

### ISSUE THREAD

**Issue by JeremyApp** [masaccio/numbers-parser#31]
I'm attempting to use version 3.0, as my workflow requires creating numbers documents and this looks like a great potential solution. While I expect it to be experimental, it appears to not work at all. I installed the main branch:

```
python3 -m pip install -e git+https://github.com/masaccio/numbers-parser.git#egg=numbers_parser
```

And then opened the interactive prompt to try and use it, but it fails immediately:

```
Python 3.9.10 (main, Jan 15 2022, 11:40:36)
Type "help", "copyright", "credits" or "license" for more information.
>>> from numbers_parser import Document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremy/src/numbers-parser/src/numbers_parser/__init__.py", line 25, in <module>
    from numbers_parser.document import Document  # NOQA
  File "/Users/jeremy/src/numbers-parser/src/numbers_parser/document.py", line 5, in <module>
    from numbers_parser.containers import ItemsList
  File "/Users/jeremy/src/numbers-parser/src/numbers_parser/containers.py", line 1, in <module>
    from numbers_parser.file import read_numbers_file
  File "/Users/jeremy/src/numbers-parser/src/numbers_parser/file.py", line 2, in <module>
    from numbers_parser.iwafile import IWAFile
  File "/Users/jeremy/src/numbers-parser/src/numbers_parser/iwafile.py", line 7, in <module>
    from numbers_parser.mapping import ID_NAME_MAP, NAME_CLASS_MAP, NAME_ID_MAP
  File "/Users/jeremy/src/numbers-parser/src/numbers_parser/mapping.py", line 662, in <module>
    NAME_CLASS_MAP, ID_NAME_MAP, NAME_ID_MAP = compute_maps()
  File "/Users/jeremy/src/numbers-parser/src/numbers_parser/mapping.py", line 648, in compute_maps
    message_type = getattr(file, message_name)
TypeError: getattr(): attribute name must be string
```

Am I installing it wrong, or is the main branch currently broken?

**Comment by masaccio** [comment]
It was installing cleanly in Travis CI but does indeed break in a clean environment as you installed. Since I have not done a commit in a week or so my guess is it's a new version of protobuf breaking things and I will take a look when I can, possibly this weekend.

A workaround is:

``` shell
pip uninstall -y protobuf
pip install protobuf==3.20.1
```

**Comment by masaccio** [comment]
Hopefully adding cells in a table works in 3.0 but adding a new sheet/table will definitely not work. The code might run but the resulting document will not load in Numbers. I'm still trying to figure out what is wrong but Numbers will throw assertions like:

```
error	21:52:29.622070+0100	Numbers	#Assert *** Assertion failure #158: -[TSPObject willModifyForUpgradeWithOptions:] /Library/Caches/com.apple.xbs/Sources/iWorkDependenciesMacOS/iWorkDependenciesMacOS-7033.0.134/shared/persistence/src/TSPObject.mm:247 Object [TSTTableModel-905687] was modified during read unexpectedly. The file format version of the document is the latest.
```

**Comment by masaccio** [comment]
Tested with protobuf versions: 4.21.1 3.20.1 3.19.4 3.17.3 3.15.8 3.12.4
