### ISSUE TITLE
Cannot open a file modified from iCloud.com

### ISSUE THREAD

**Issue by adriengivry** [masaccio/numbers-parser#36]
## Description
Opening a file that has been edited from iCloud.com throw a `FileError` exception (`[FILENAME]: File is not a zip file`)

## Environment
- Device: Windows 11 Pro (22000.795)
- numbers-parser: [v3.0.0](https://github.com/masaccio/numbers-parser/releases/tag/v3.0.0)
- Python: 3.10.5

## Reproduction Steps
**Reproduction Rate:** 100%
1. Create an Apple Numbers spreadsheet in an iCloud folder
2. Edit it from iCloud.com
4. Load it with `numbers-parser`:
```python
doc = Document("C:\\Users\\adrie\\iCloudDrive\\foobar.numbers")
```

## Stack Trace
```
Traceback (most recent call last):
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\file.py", line 32, in read_numbers_file
    zipf = ZipFile(path)
  File "C:\Users\adrie\scoop\apps\python310\current\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\adrie\scoop\apps\python310\current\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\document.py", line 28, in __init__
    self._model = _NumbersModel(filename)
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\model.py", line 77, in __init__
    self.objects = ObjectStore(filename)
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\containers.py", line 53, in __init__
    read_numbers_file(
  File "C:\Users\adrie\scoop\apps\python310\current\lib\site-packages\numbers_parser\file.py", line 34, in read_numbers_file
    raise FileError(f"{path}: " + str(e))
numbers_parser.exceptions.FileError: C:\Users\adrie\iCloudDrive\foobar.numbers: File is not a zip file
```

## Linked Issues
This issue has been previously mentioned here: https://github.com/masaccio/numbers-parser/issues/32

**Comment by masaccio** [comment]
Wondering if I missed merging the branch to main, though seems like a different problem (odd the .numbers file is not recognised as a Zip). I am away from my computer for a bit so will be September for a fix. 

Only other thing I can think of is the file wasn’t fully synced from iCloud perhaps? Just speculation without me looking though. 

>

**Comment by adriengivry** [comment]
After further investigations, I've noticed that after editing a spreadsheet with iCloud.com, this spreadsheet size goes to 0 bytes on Windows, and 256 bytes on MacOS. I think Apple is only storing a link or a pointer kind of thing to the actual file on iCloud. This issue is then on Apple's side. I really hope they can fix that!
